const ActionTypes = {

    CREATE_TODO: "CREATE_TODO",
    CREATE_TODO_SUCCESS: "CREATE_TODO_SUCCESS",
    CREATE_TODO_FAILED: "CREATE_TODO_FAILED",

    GET_TODO: "GET_TODO",
    GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
    GET_TODO_FAILED: "GET_TODO_FAILED",

    UPDATE_TODO: "UPDATE_TODO",
    UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
    UPDATE_TODO_FAILED: "UPDATE_TODO_FAILED",

    DELETE_TODO: "DELETE_TODO",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    DELETE_TODO_FAILED: "DELETE_TODO_FAILED",

}

export { ActionTypes }